site_name: Port
site_url: https://portdic.com
nav:
  - Home: index.md
  - Learn: learn.md
  - Packages: package.md
  - Dictionary: portdic.md
  - Commands: commands.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list 
theme:
  name: null
  custom_dir: 'cinder'
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate