site_name: Port
site_url: https://portget.com
nav:
  - Home: index.md
  - PortDic : portdic.md
  - Relation: relation.md
  - API Reference: reference.md
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list

theme:
  name: null
  custom_dir: 'cinder'