site_name: Port
site_url: https://example.com/
nav:
  - API Reference: reference.md
  - Relation: relation.md
  - About: about.md
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list

theme:
  name: null
  custom_dir: 'cinder'