site_name: Port
site_url: https://portdic.com
nav:
  - Home: index.md
  - Learn: learn.md
  - Dictionary: portdic.md
  - SDK: sdk.md
  - API Reference: reference.md
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list

theme:
  name: null
  custom_dir: 'cinder'