site_name: Port
site_url: https://portdic.com
nav:
  - Home: index.md
  - Getting Started:
    - Learn: learn.md
    - .Net: dotnet.md
    - React: react.md
  - Documentation:
    - Commands: commands.md
    - Remote Access: remote.md
  - Protocols: 
    - OPC UA: opcua.md
    - Modbus: modbus.md
    - EtherNet/IP: ethernetip.md
    - SECS: secs.md
    - RTSP: rtsp.md
    - MQTT: mqtt.md
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  logo: img/logo.ico
  favicon: img/logo.ico
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search:
      lang: en

extra_css:
  - extra_css.css

# Disable generator but keep copyright
copyright: ""