site_name: Port
site_url: https://example.com/
nav:
  - Started: started.md
  - Relation: relation.md
  - About: about.md
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true