site_name: Port
site_url: https://portdic.com
nav:
  - Home: index.md
  - Learn: learn.md
  - Packages: package.md
  - Dictionary: portdic.md
  - Commands: commands.md
  - Supported: supported.md
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - attr_list

theme:
  name: null
  custom_dir: 'cinder'