[tool.poetry]
name = "portdoc"
version = "0.0.1"
description = "port document"
authors = ["portget <portroconn@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
