// Auto-generated by Port. Do not edit manually.

namespace sample
{
    public static class Io
    {
        public const string Bulb1OnOff = "Bulb1OnOff";
        public const string Bulb2OnOff = "Bulb2OnOff";
        public const string Bulb1Temp = "Bulb1Temp";
        public const string Bulb2Temp = "Bulb2Temp";
    }
}
